Vagrant.configure("2") do |config|
    config.vm.define "vault" do |vault|
        vault.vm.box = "spox/ubuntu-arm"
        vault.vm.box_version = "1.0.0"
        vault.vm.network "forwarded_port", guest: 8200, host: 8200
        vault.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
            vb.cpus = 2
        end
        vault.vm.provision "file", source: "./config/vault.hcl", destination: "/tmp/vault.hcl"
        vault.vm.provision "file", source: "./config/vault.service", destination: "/tmp/vault.service"
        vault.vm.provision "shell", path: "./install-vault/install-vault-ubu.sh"
        vault.vm.provision "shell", inline: "sudo systemctl enable vault"
        vault.vm.provision "shell", inline: "sudo systemctl start vault"
  end
end