rules:
  - id: aws-api-gateway-v2-misconfigured-cors
    patterns:
      - pattern: |
          resource "aws_apigatewayv2_api" $ANYTHING {
            ...
            cors_configuration {
              ...
              allow_origins     = ["*"]
              ...
            }
            ...
          }
      - pattern-not: |
          resource "aws_apigatewayv2_api" $ANYTHING {
            ...
            cors_configuration {
              ...
              allow_origins     = ["*"]
              ...
            }
            ...
          }
    message: "Insecure Cross-Origin Resource Sharing Configuration Found - Allowing All Domains"
    severity: WARNING
    languages: [terraform]
    metadata:
      domain: Security Best Practices
      resource: aws_apigatewayv2_api
      resource-type: API Gateway V2
      resource-category: Virtual Network
      reference_id: AC_AWS_0467
      version: 1
