rules:
  - id: kinesis-sse-not-configured
    patterns:
      - pattern: |
          resource "aws_kinesis_firehose_delivery_stream" $ANYTHING {
            ...
            server_side_encryption = {  # SSE configuration
              ...
            }
            ...
          }
      - pattern-not: |
          resource "aws_kinesis_firehose_delivery_stream" $ANYTHING {
            ...
            server_side_encryption {
              key_arn = "arn:aws:kms:us-east-1:123456789012:key/my-kms-key-id"
            }
            ...
          }
    message: "Ensure AWS Kinesis Firehose delivery stream has server-side encryption (SSE) configured."
    severity: HIGH
    languages: [terraform]
    metadata:
      domain: Data Protection
      resource: aws_kinesis_firehose_delivery_stream
      resource-type: Kinesis Firehose
      reference_id: AWS.Kinesis.EncryptionandKeyManagement.High.0411
      version: 2
