rules:
  - id: config-enabled-for-all-regions
    patterns:
      - pattern: |
          resource "aws_config_configuration_recorder" $ANYTHING {
            ...
            recording_group {
              all_supported = false  # Not enabled for all regions
              ...
            }
            ...
          }
      - pattern-not: |
          resource "aws_config_configuration_recorder" $ANYTHING {
            ...
            recording_group {
              all_supported = true  # Enabled for all regions
              ...
            }
            ...
          }
    message: "Ensure AWS Config is enabled in all regions."
    severity: MEDIUM
    languages: [terraform]
    metadata:
      domain: Logging and Monitoring
      resource: aws_config_configuration_recorder
      resource-type: Config
      reference_id: AWS.Config.Logging.Medium.0590
      version: 2
