name: VM Image Builder

on:
  pull_request:
    paths:
      - "the0x-labs/images/packer/VM/**/*"

permissions:
  pull-requests: write

jobs:
  packer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get list of changed files
      id: changed-files
      run: |
        git fetch origin ${{ github.event.before }} --depth=1
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
        cat changed_files.txt

    - name: Filter image files
      id: filter-images
      run: |
        grep '/the0x-labs/images/' changed_files.txt > image_files.txt
        cat image_files.txt

    - name: Install Packer
      if: steps.filter-images.outputs.image_files != ''
      run: |
        wget https://releases.hashicorp.com/packer/1.7.4/packer_1.7.4_linux_amd64.zip
        unzip packer_1.7.4_linux_amd64.zip
        sudo mv packer /usr/local/bin/packer
        packer --version

    - name: Build Images
      if: steps.filter-images.outputs.image_files != ''
      id: build-images
      run: |
        while IFS= read -r file; do
          echo "Building image for $file"
          packer build -machine-readable $file | tee output.log
        done < image_files.txt

    - name: Extract AMI ID
      if: steps.filter-images.outputs.image_files != ''
      id: extract-ami-id
      run: |
        AMI_ID=$(grep -oP 'artifact,0,id,ami-\K[^ ]+' output.log)
        echo "AMI_ID=$AMI_ID" >> $GITHUB_ENV
        echo "AMI ID: $AMI_ID"

    - name: Run Trivy Scan
      if: steps.filter-images.outputs.image_files != ''
      uses: docker://aquasec/trivy:latest
      with:
        args: vm --scanners vuln ami:$AMI_ID
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Convert Trivy Report to PDF
      if: steps.filter-images.outputs.image_files != ''
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-xetex
        pandoc trivy-report.json -o trivy-report.pdf

    - name: Upload PDF Report
      if: steps.filter-images.outputs.image_files != ''
      uses: actions/upload-artifact@v3
      with:
        name: trivy-report
        path: trivy-report.pdf