name: Publish Semgrep Rules

on:
  push:
    branches:
      - main
    paths:
      - '/the0x-labs/security/semgrep/rules/**'
  workflow_dispatch:

concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: false

jobs:
  publish-rules:
    name: publish-private-semgrep-rules
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep:latest

    steps:
      - name: Check for modified rules
        id: check_modified
        run: |
          # Get list of modified rule files
          MODIFIED_RULES=$(git diff --name-only HEAD^ HEAD -- semgrep/rules/)

          if [ -z "$MODIFIED_RULES" ]; then
              echo "No modified rules to publish, exiting job..."
              exit 78
          else
              echo "Modified rules: $MODIFIED_RULES"
              echo "::set-output name=modified_rules::$MODIFIED_RULES"
          fi
      
      - name: Publish Modified Semgrep Rules
        run: |
          # Publish only the modified rules
          for rule in ${{ steps.check_modified.outputs.modified_rules }}; do
              echo "Publishing rule: $rule"
              semgrep publish --visibility=org_private $rule
          done
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
